### PR TITLE
556 Channel value issue with zero value

### LINKED ISSUE #556: Channel value issue with zero value
#### Describe the bug

If you pass 0 as a value for the channel value component, it won't display the value.

#### What is the expected behavior?

The 0 value is visible

#### What are the steps to reproduce?

Pass 0 has value to the component (see code snippet below).

#### Screenshots / Screen recording

channel-value

#### Code snippet / Link to minimum reproduction example
```
<blui-channel-value
  [value]="0"
  [units]="'kWh'"
>
</blui-channel-value>

```

#### Your environment information
```
    "@brightlayer-ui/angular-components": "7.0.3",
    "@brightlayer-ui/angular-themes": "7.0.1",
    "@brightlayer-ui/chartjs": "^1.0.0",
    "@brightlayer-ui/colors": "3.1.1",
    "@brightlayer-ui/icons": "1.11.0",
    "@brightlayer-ui/ng-progress-icons": "1.2.1",
```

#### Suggested fix

My assumption is that there is a if condition that check the value but 0 will return false therefore hiding the value.

### PR DESCRIPTION
**Pull request by raghavenc5**
Fixes #556 .

#### Changes proposed in this Pull Request:
- Check the input value type as string or number then convert into string if number as 0
- 
- 

#### Screenshots / Screen Recording (if applicable)
-
image

#### To Test:
- yarn start

#### Any specific feedback you are looking for?
-

### CODE REVIEW

File: src/lib/core/channel-value/channel-value.component.ts [hunk 1]
```diff
@@ -2,6 +2,7 @@ import { ChangeDetectionStrategy, Component, Input, OnChanges, ViewEncapsulation
 import { requireInput } from '../../utils/utils';
 
 export type UnitSpaceType = 'show' | 'hide' | 'auto';
+//console.log(value);
```
Comment (daileytj) [inline src/lib/core/channel-value/channel-value.component.ts:5]: Let's make sure we clean up our console logs

File: src/lib/core/channel-value/channel-value.component.ts [hunk 2]
```diff
@@ -81,4 +89,12 @@ export class ChannelValueComponent implements OnChanges {
...
             : this.suffixUnitWhitelist.includes(this.units);
     }
+
+    /** Update the text of the Channel value element in the DOM, creating the element if necessary. */
+    private _updateRenderedValue(newValue: string | number): void {
+        const newValueNormalized: any = `${newValue ?? ''}`.trim();
+
+        // Check the value as interger and convert into the string value
+        this._value = !isNaN(Number(newValueNormalized)) ? String(newValueNormalized) : newValueNormalized;
+    }
```
Comment (daileytj) [inline src/lib/core/channel-value/channel-value.component.ts:99]: This feels like overkill. I would have gone with a simpler approach where you render `{{ getValueAsString() }}` instead of `{{ value }}` in the component template and then use a simple function like this to return the value as a string: 

`getValueAsString(): string {
        return String(this.value);
    }`

If we wanted to make it generic we could take in a value for the getValueAsString function and convert that instead. Feel free to state your case on why your approach is preferred.

File: src/lib/core/channel-value/channel-value.component.ts [hunk 3]
```diff
@@ -53,7 +54,14 @@ export class ChannelValueComponent implements OnChanges {
...
     /** The text to display for the value (bold text)*/
-    @Input() value: string | number;
+    @Input('value')
+    get value(): string | number {
+        return this._value;
+    }
+    set value(newValue: string | number) {
+        this._updateRenderedValue(newValue);
+    }
+    private _value: string | number;
```
Comment (daileytj) [inline src/lib/core/channel-value/channel-value.component.ts:64]: We should be able to achieve this fix without the need for a getter and setter on that input.

**Review by daileytj — COMMENTED** [review]
As Suraj mentioned, you may want to check your prettier config or run `yarn prettier` prior to making commits so they are in line with our code-standards. Great job adding a test case for this!

**Review by daileytj — APPROVED** [review]
